Better blind bug handling

diff --git a/builder/data/usr/bin/bettercap-launcher b/builder/data/usr/bin/bettercap-launcher
--- a/builder/data/usr/bin/bettercap-launcher
+++ b/builder/data/usr/bin/bettercap-launcher
@@ -9,16 +9,31 @@ if is_crypted_mode; then
   done
 fi
 
+# check if wifi driver is stuck
+if ! stuck_brcm; then
+  echo "Could not reload wifi driver. Reboot"
+  reboot
+fi
+
 # check if wifi driver is bugged
 if ! check_brcm; then
   if ! reload_brcm; then
-    echo "Could not reload wifi driver. Reboot"
-    reboot
+    echo "Could not reload wifi driver."
+    exit 1
   fi
   sleep 10
 fi
 
+#relad wifi driver once
+echo "Reloading wifi driver"
+if ! reload_brcm; then
+  echo "Could not reload wifi driver."
+  exit 1
+fi
+sleep 3
+
 # start mon0
+echo "enable mon0"
 start_monitor_interface
 
 if is_auto_mode_no_delete; then
